# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buier',
            fields=[
                ('bID', models.AutoField(primary_key=True, serialize=False, verbose_name='买家ID')),
                ('bName', models.CharField(max_length=20, verbose_name='买家姓名')),
                ('bPhone', models.CharField(max_length=30, verbose_name='买家电话')),
                ('bDetail', models.CharField(max_length=300, verbose_name='备注')),
                ('bCount', models.CharField(max_length=30, verbose_name='厅室数量')),
                ('bPrice', models.IntegerField(verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False, verbose_name='客户ID')),
                ('cName', models.CharField(max_length=30, verbose_name='姓名')),
                ('cPhone', models.CharField(max_length=30, verbose_name='手机号码')),
                ('cDetail', models.CharField(default='', max_length=300, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False, verbose_name='小区ID')),
                ('cAddress', models.CharField(max_length=200, verbose_name='小区地址')),
                ('cName', models.CharField(max_length=200, verbose_name='小区名字')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('hID', models.AutoField(primary_key=True, serialize=False, verbose_name='房屋ID')),
                ('hType', models.IntegerField(default=3, verbose_name='权限级别')),
                ('hDetail', models.CharField(default='', max_length=300, verbose_name='备注')),
                ('hPosition', models.CharField(max_length=50, verbose_name='地址')),
                ('hArea', models.IntegerField(verbose_name='面积')),
                ('hFloor', models.IntegerField(verbose_name='楼层')),
                ('hLowPrice', models.IntegerField(verbose_name='最低价格')),
                ('hPrice', models.IntegerField(verbose_name='建议价格')),
                ('hDecoration', models.CharField(max_length=100, verbose_name='装修类型')),
                ('hHouseType', models.CharField(max_length=100, verbose_name='房屋类型')),
                ('hCount', models.CharField(max_length=100, verbose_name='厅室数量')),
                ('hDate', models.DateField(verbose_name='记录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pName', models.CharField(max_length=20, verbose_name='用户名')),
                ('pID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('pType', models.IntegerField(default=3, verbose_name='用户权限')),
                ('pEmail', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('pPassword', models.CharField(max_length=500, verbose_name='密码')),
                ('pPhone', models.CharField(max_length=30, verbose_name='手机号码')),
                ('pLastLogin', models.DateField(verbose_name='上次登录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('iID', models.AutoField(primary_key=True, serialize=False, verbose_name='图片ID')),
                ('iPath', models.CharField(max_length=300, verbose_name='图片路径')),
                ('iUpFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluData.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='pHead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluData.Pictures'),
        ),
        migrations.AddField(
            model_name='house',
            name='hBelong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluData.Person'),
        ),
        migrations.AddField(
            model_name='house',
            name='hClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluData.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='cBelong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluData.Person'),
        ),
        migrations.AddField(
            model_name='buier',
            name='bCommunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluData.Community'),
        ),
    ]
