# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buier',
            name='bCommunity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fluData.Community'),
        ),
        migrations.AlterField(
            model_name='buier',
            name='bCount',
            field=models.CharField(blank=True, max_length=30, verbose_name='厅室数量'),
        ),
        migrations.AlterField(
            model_name='buier',
            name='bDetail',
            field=models.CharField(blank=True, max_length=300, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='buier',
            name='bPrice',
            field=models.IntegerField(blank=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cDetail',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hCount',
            field=models.CharField(blank=True, max_length=100, verbose_name='厅室数量'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hDecoration',
            field=models.CharField(blank=True, max_length=100, verbose_name='装修类型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hDetail',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hHouseType',
            field=models.CharField(blank=True, max_length=100, verbose_name='房屋类型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hPrice',
            field=models.IntegerField(blank=True, verbose_name='建议价格'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pEmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pLastLogin',
            field=models.DateField(blank=True, verbose_name='上次登录时间'),
        ),
    ]
