# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0002_auto_20170726_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='iUpFrom',
        ),
        migrations.AlterField(
            model_name='person',
            name='pHead',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fluData.Pictures'),
        ),
    ]
