# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0003_auto_20171007_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pHead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fluData.Pictures'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pLastLogin',
            field=models.DateField(blank=True, null=True, verbose_name='上次登录时间'),
        ),
    ]
