# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0004_auto_20171007_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cBelong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluData.Person'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cDetail',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cName',
            field=models.CharField(max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cPhone',
            field=models.CharField(max_length=30, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pPassword',
            field=models.CharField(max_length=500, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pPhone',
            field=models.CharField(max_length=30, null=True, verbose_name='手机号码'),
        ),
    ]
