# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0005_auto_20171007_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='tHouse',
            fields=[
                ('tID', models.AutoField(primary_key=True, serialize=False, verbose_name='房源ID')),
                ('tName', models.CharField(max_length=200, verbose_name='客户姓名')),
                ('tPhone', models.CharField(max_length=100, verbose_name='客户电话')),
                ('tPrice', models.CharField(max_length=100, verbose_name='价格')),
                ('tCommunity', models.CharField(max_length=100, verbose_name='小区')),
                ('tPos', models.CharField(max_length=100, verbose_name='位置')),
                ('tArea', models.CharField(max_length=100, verbose_name='面积')),
                ('tType', models.CharField(max_length=100, verbose_name='户型')),
                ('tOther', models.CharField(max_length=1000, verbose_name='备注')),
            ],
        ),
    ]
