# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0006_thouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buier',
            name='bCommunity',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cBelong',
        ),
        migrations.RemoveField(
            model_name='house',
            name='hBelong',
        ),
        migrations.RemoveField(
            model_name='house',
            name='hClient',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pHead',
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tArea',
            field=models.CharField(max_length=100, null=True, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tCommunity',
            field=models.CharField(max_length=100, null=True, verbose_name='小区'),
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tName',
            field=models.CharField(max_length=200, null=True, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tOther',
            field=models.CharField(max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tPhone',
            field=models.CharField(max_length=100, null=True, verbose_name='客户电话'),
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tPos',
            field=models.CharField(max_length=100, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tPrice',
            field=models.CharField(max_length=100, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='thouse',
            name='tType',
            field=models.CharField(max_length=100, null=True, verbose_name='户型'),
        ),
        migrations.DeleteModel(
            name='Buier',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
