# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='手机号码')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='售价')),
                ('price_unit', models.CharField(choices=[('万元', 'W'), ('千元', 'K'), ('百元', 'H'), ('  元', 'Y')], default='W', max_length=20, null=True, verbose_name='售价单位')),
                ('house_type', models.CharField(choices=[('出售', 'SELL'), ('出租', 'RENT')], default='出售', max_length=20, null=True, verbose_name='类型')),
                ('keys', models.CharField(default='', max_length=40, null=True, verbose_name='钥匙位置')),
                ('community', models.CharField(default='', max_length=50, null=True, verbose_name='社区')),
                ('position', models.CharField(default='', max_length=200, null=True, verbose_name='地址')),
                ('area', models.IntegerField(default=0, null=True, verbose_name='面积')),
                ('kind', models.CharField(default='', max_length=50, null=True, verbose_name='户型')),
                ('more', models.CharField(default='', max_length=1000, null=True, verbose_name='备注')),
                ('floor', models.IntegerField(default=0, null=True, verbose_name='楼层')),
                ('level', models.IntegerField(default=3, null=True, verbose_name='等级')),
                ('status', models.CharField(choices=[('交易完成', '该交易已在本店完成'), ('失效', '该房源已失效（已出售或出租）'), ('有效', '该房源有效')], default='有效', max_length=20, null=True, verbose_name='资源状态')),
                ('decor', models.CharField(choices=[('清水', '清水'), ('简装', '简装'), ('中装', '中装'), ('精装', '精装'), ('豪装', '豪装')], default='', max_length=50, null=True, verbose_name='装修情况')),
                ('belong', models.IntegerField(default=1, null=True, verbose_name='所有者')),
            ],
        ),
    ]
