# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0010_auto_20171106_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='tHouse',
        ),
        migrations.AddField(
            model_name='house',
            name='all_things',
            field=models.TextField(default='', null=True, verbose_name='搜索信息'),
        ),
    ]
