# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 04:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0012_auto_20171118_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='change_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 18, 4, 6, 4, 822981, tzinfo=utc), null=True, verbose_name='上次修改时间'),
        ),
    ]
