# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0013_auto_20171118_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='change_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('万元', '万元'), ('千元', '千元'), ('百元', '百元'), ('  元', '元')], default='万元', max_length=20, null=True, verbose_name='售价单位'),
        ),
    ]
