# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluData', '0014_auto_20171118_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='all_things',
            field=models.TextField(blank=True, default='暂无', null=True, verbose_name='搜索信息'),
        ),
        migrations.AlterField(
            model_name='house',
            name='community',
            field=models.CharField(blank=True, default='暂无', max_length=50, null=True, verbose_name='社区'),
        ),
        migrations.AlterField(
            model_name='house',
            name='decor',
            field=models.CharField(blank=True, choices=[('清水', '清水'), ('简装', '简装'), ('中装', '中装'), ('精装', '精装'), ('豪装', '豪装'), ('暂无', '暂无')], default='暂无', max_length=50, null=True, verbose_name='装修情况'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='house',
            name='ikeys',
            field=models.CharField(blank=True, default='暂无', max_length=40, null=True, verbose_name='钥匙位置'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kind',
            field=models.CharField(blank=True, default='暂无', max_length=50, null=True, verbose_name='户型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='more',
            field=models.CharField(blank=True, default='暂无', max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='house',
            name='phone',
            field=models.CharField(blank=True, default='暂无', max_length=20, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='house',
            name='position',
            field=models.CharField(blank=True, default='暂无', max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastCheck',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次签到时间'),
        ),
    ]
